ALTER TABLE FACTSales
ADD CONSTRAINT FK_CUSTOMER_ID 
FOREIGN KEY (customerID) REFERENCES [dbo].[DimCustomer1](customerID);

ALTER TABLE FACTSales
ADD CONSTRAINT FK_PAYMENT_ID 
FOREIGN KEY (paymentID) REFERENCES [dbo].[DiMPayment1](paymentID);


ALTER TABLE FACTSales
ADD CONSTRAINT FK_PRODUCT_ID 
FOREIGN KEY (prodectID) REFERENCES [dbo].[DiMProducts1](prodectID);

ALTER TABLE FACTSales
ADD CONSTRAINT FK_PROMO_ID 
FOREIGN KEY (promoID) REFERENCES [dbo].[DiMPromo1](promoID);

ALTER TABLE FACTSales
ADD CONSTRAINT FK_RATING_ID 
FOREIGN KEY (ratingID) REFERENCES [dbo].[DiMRating1](ratingID);

ALTER TABLE FACTSales
ADD CONSTRAINT FK_SHIPPING_ID 
FOREIGN KEY (shippingID) REFERENCES [dbo].[DimShipping1](shippingID);
